services:
  video-editor:
    image: aimercat1994/nas-video-editor:latest
    container_name: video-editor
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - /vol1/1000/Alist:/videos/Alist
      - /vol1/1000/Bililive:/videos/Bililive
      - video-editor-data:/data
    environment:
      - PASSWORD=shuzhiyu13
      - TZ=Asia/Shanghai
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"    # video group (getent group video)
      - "105"   # render group (getent group render)

volumes:
  video-editor-data:
